build: off

cache:
 - "%LOCALAPPDATA%\\Yarn"

environment:
  matrix:
    - nodejs_version: '8'
      test_script: 'test -- features/background.feature:26'
    - nodejs_version: '6'
      test_script: 'test'
    - nodejs_version: '4'
      test_script: 'feature-test -- --profile node-4'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node -e 'console.log(process.env)'
  - node --version
  - yarn --version
  - yarn run %test_script%
